apiVersion: v1
kind: Service
metadata:
  name: version-get
  labels:
    app: version-get
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: version-get
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-get-deployment
  labels:
    app: version-get
spec:
  replicas: 10
  selector:
    matchLabels:
      app: version-get
  template:
    metadata:
      labels:
        app: version-get
    spec:
      containers:
      - name: version-get
        image: ORG/version-get:test2
        ports:
        - containerPort: 3000
        env:
            - name: VERSION
              value: '333'